local Players = game:GetService("Players")
local RunService = game:GetService("RunService")

local localPlayer = Players.LocalPlayer
local espFolder = Instance.new("Folder", localPlayer.PlayerGui)
espFolder.Name = "ESP"

local boxes = {}

RunService.RenderStepped:Connect(function()
    for _, player in pairs(Players:GetPlayers()) do
        if player ~= localPlayer and player.Team ~= localPlayer.Team then
            local char = player.Character
            local hrp = char and char:FindFirstChild("HumanoidRootPart")
            if hrp then
                if not boxes[player] then
                    local box = Instance.new("BoxHandleAdornment")
                    box.Adornee = hrp
                    box.Size = Vector3.new(4,6,1)
                    box.Color3 = Color3.new(1,0,0)
                    box.Transparency = 0.5
                    box.AlwaysOnTop = true
                    box.Parent = espFolder
                    boxes[player] = box
                else
                    boxes[player].Adornee = hrp
                end
            elseif boxes[player] then
                boxes[player]:Destroy()
                boxes[player] = nil
            end
        elseif boxes[player] then
            boxes[player]:Destroy()
            boxes[player] = nil
        end
    end
end)
